"""Add Payment model

Revision ID: b99d9623d15a
Revises: 40118a0bf56c
Create Date: 2025-11-12 22:07:41.822460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99d9623d15a'
down_revision = '40118a0bf56c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checkout_request_id', sa.String(length=100), nullable=True),
    sa.Column('merchant_request_id', sa.String(length=100), nullable=True),
    sa.Column('mpesa_receipt_number', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('account_reference', sa.String(length=100), nullable=True),
    sa.Column('transaction_desc', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result_code', sa.String(length=10), nullable=True),
    sa.Column('result_desc', sa.String(length=255), nullable=True),
    sa.Column('plan_type', sa.String(length=20), nullable=True),
    sa.Column('subscription_activated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_checkout_request_id'), ['checkout_request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_mpesa_receipt_number'), ['mpesa_receipt_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_mpesa_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_payments_checkout_request_id'))

    op.drop_table('payments')
    # ### end Alembic commands ###
